
print "\n\t\t#################################################"
print "\t\t#                                               #"
print "\t\t#                    ABOUT                      #"
print "\t\t#                                               #"
print "\t\t#################################################"

print"\nTHIS TOOL IS MADE BY NISARG JANI AND OTHER HELP IS DONE BY NIKESH NAYAK"
print"\nYOU CAN DOWNLOAD THIS TOOL FROM SOURCE FORGE"
print"\nTHIS TOOL IS MADE FOR ONLY ETHICAL HACKERS TO PENTEST"
print"\nWE GAVE OUR BEST TO MAKE THIS TOOL TO USE EASILY AND ROOKIES CAN USE THIS EASILY"
print"\nAND ALSO YOU DON't HAVE TO REMEMBER THOSE HARD SYNTAX OR COMMANDS TO PENTEST OR USE TOOLS"
print"\nWE HAVE DIVIDED THIS TOOL IN THREE PARTS WEB , NETWORK ,COMPUTER"
print"\nMAINLY WE CAN SAY THAT FOR VULNRABLITY TESTING OF YOUR WEBSITE OR NETWORK OR PC"
print"\nTHIS TOOL IS MADE FOR ONLY GOOD PURPOSE IF YOU WILL USE IT FOR BAD PURPOSE WE WILL NOT RESPONSIBLE FOR THAT"
print"\nTHIS TOOL IS FREE AND OPEN SOURCE SO ANYONE CAN CHANGE IN THE SOURCE CODE"
print"\nFOR ANY KIND OF HELP YOU CAN EMAIL US AT nisargjani20996@gmail.com ALSO YOU CAN WHATSAPP AT 9909727302"
print"\nWE WILL ADD NEW FEATURES IN NEXT VERSION LIKE ADMIN PANEL CRACKING,ONE CLICK EXPLOIT AND MANY OTHERS"
print"\nSO GUYS ENJOY THESE TOOL !!!"
print"\nAND NEW SUGGESTIONS WILL BE APPERCIATED....."






input("\n[+]PRESS ANY KEY TO EXIT")
